import type { Metadata } from "next";
import { DotGothic16, Geist, Geist_Mono, Kiwi_Maru, Shippori_Mincho_B1 } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dotGothic = DotGothic16({
  weight: ['400'],
  style: ['normal'],
});

const shipporiMincho = Shippori_Mincho_B1({
  weight: ['400'],
  style: ['normal'],
});

const kiwiMaru = Kiwi_Maru({
  weight: ['400'],
  style: ['normal'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
